SELECT count(DISTINCT(KODE_SATKER)) from MP_CUSTOMER_SSC;

SELECT count(*) FROM MP_SATKER_GENERATE

-- dirunning bulanan utk menjadi list generate pdf djpb
truncate table MP_SATKER_GENERATE;

INSERT into MP_SATKER_GENERATE SELECT DISTINCT(KODE_SATKER),1 from MP_CUSTOMER_SSC;

--CREATE TABLE MP_TTE_SATKER_BKP_042023 AS SELECT * FROM MP_TTE_SATKER;

truncate table MP_TTE_SATKER;

INSERT into MP_TTE_SATKER SELECT DISTINCT(KODE_SATKER),9 from MP_CUSTOMER_SSC;

-- INSERT into MP_TTE_SATKER SELECT kode_satker,9 from mp_satker_generate;

commit;

-- ini hanya tambahan
SELECT * from MP_SATKER_GENERATE where kode_satker not in (SELECT SATKER_ID from PDF_DETAIL_PRODUK_CURRENT)



SELECT * from PDF_DETAIL_PRODUK_CURRENT;

SELECT * FROM MP_TTE_SATKER WHERE STATUS =9

UPDATE MP_TTE_SATKER SET STATUS =9 WHERE SATKER IN ('411651');

UPDATE MP_satker_generate SET STATUS =1 WHERE KODE_SATKER IN ('411651');

SELECT DISTINCT(KODE_SATKER) FROM MP_SATKER_GENERATE WHERE STATUS=1 order by KODE_SATKER

COMMIT;

COMMIT;